[package]
name = "fcm-futures3"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
description = "An API to talk to FCM (Firebase Cloud Messaging) in Rust"
license = "MIT"
repository = "https://github.com/jbg/fcm-rust"
keywords = ["fcm", "firebase", "cloud", "messaging", "tokio"]

[dependencies]
chrono = "0.4"
erased-serde = "0.3"
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
reqwest = { version = "0.9.17", default-features = false, features = ["rustls-tls", "trust-dns"] }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio-service = "0.1"

[dev-dependencies]
argparse = "0.2.1"
tokio = "0.1"
