[package]
name = "fcm-futures3"
version = "0.1.0"
authors = ["Jasper Bryant-Greene <jbg@rf.net.nz>"]
description = "An API to talk to FCM (Firebase Cloud Messaging) in Rust"
license = "MIT"
repository = "https://github.com/jbg/fcm-rust"
keywords = ["fcm", "firebase", "cloud", "messaging", "tokio"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
erased-serde = "0.3"
serde_derive = "1.0"
futures-preview = { version = "0.3.0-alpha.15", features = ["compat"] }
tokio-service = "0.1"
hyper = "0.12"
http = "0.1"
chrono = "0.4"

[dev-dependencies]
argparse = "0.2.1"
tokio = "0.1"
